'p: android_alarm_manager':
  - packages/android_alarm_manager/**/*

'p: android_intent':
  - packages/android_intent/**/*

'p: battery':
  - packages/battery/**/*

'p: camera':
  - packages/camera/**/*

'p: connectivity':
  - packages/connectivity/**/*

'p: cross_file':
  - packages/cross_file/**/*

'p: device_info':
  - packages/device_info/**/*

'p: espresso':
  - packages/espresso/**/*

'p: file_selector':
  - packages/file_selector/**/*

'p: flutter_plugin_android_lifecycle':
  - packages/flutter_plugin_android_lifecycle/**/*

'p: google_maps_flutter':
  - packages/google_maps_flutter/**/*

'p: google_sign_in':
  - packages/google_sign_in/**/*

'p: image_picker':
  - packages/image_picker/**/*

'p: in_app_purchase':
  - packages/in_app_purchase/**/*

'p: ios_platform_images':
  - packages/ios_platform_images/**/*

'p: local_auth':
  - packages/local_auth/**/*

'p: package_info':
  - packages/package_info/**/*

'p: path_provider':
  - packages/path_provider/**/*

'p: plugin_platform_interface':
  - packages/plugin_platform_interface/**/*

'p: quick_actions':
  - packages/quick_actions/**/*

'p: sensors':
  - packages/sensors/**/*

'p: share':
  - packages/share/**/*

'p: shared_preferences':
  - packages/shared_preferences/**/*

'p: url_launcher':
  - packages/url_launcher/**/*

'p: video_player':
  - packages/video_player/**/*

'p: webview_flutter':
  - packages/webview_flutter/**/*

'p: wifi_info_flutter':
  - packages/wifi_info_flutter/**/*

'platform-android':
  - packages/*/*_android/**/*
  - packages/**/android/**/*

'platform-ios':
  - packages/*/*_ios/**/*
  - packages/**/ios/**/*

'platform-linux':
  - packages/*/*_linux/**/*
  - packages/**/linux/**/*

'platform-macos':
  - packages/*/*_macos/**/*
  - packages/**/macos/**/*

'platform-web':
  - packages/*/*_web/**/*
  - packages/**/web/**/*

'platform-windows':
  - packages/*/*_windows/**/*
  - packages/**/windows/**/*
