// Mocks generated by Mockito 5.1.0 from annotations
// in webview_flutter_wkwebview/test/src/web_kit/web_kit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:webview_flutter_wkwebview/src/common/web_kit.pigeon.dart'
    as _i6;
import 'package:webview_flutter_wkwebview/src/web_kit/web_kit.dart' as _i3;
import 'package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart'
    as _i2;

import '../test_web_kit.pigeon.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWKWebsiteDataStoreHostApiImpl_0 extends _i1.Fake
    implements _i2.WKWebsiteDataStoreHostApiImpl {}

/// A class which mocks [WKWebsiteDataStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockWKWebsiteDataStore extends _i1.Mock
    implements _i3.WKWebsiteDataStore {
  MockWKWebsiteDataStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WKWebsiteDataStoreHostApiImpl get websiteDataStoreHostApi =>
      (super.noSuchMethod(Invocation.getter(#websiteDataStoreHostApi),
              returnValue: _FakeWKWebsiteDataStoreHostApiImpl_0())
          as _i2.WKWebsiteDataStoreHostApiImpl);
  @override
  _i4.Future<void> removeDataOfTypes(
          Set<_i3.WKWebsiteDataTypes>? dataTypes, DateTime? since) =>
      (super.noSuchMethod(
          Invocation.method(#removeDataOfTypes, [dataTypes, since]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}

/// A class which mocks [TestWKWebsiteDataStoreHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestWKWebsiteDataStoreHostApi extends _i1.Mock
    implements _i5.TestWKWebsiteDataStoreHostApi {
  MockTestWKWebsiteDataStoreHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void createFromWebViewConfiguration(
          int? instanceId, int? configurationInstanceId) =>
      super.noSuchMethod(
          Invocation.method(#createFromWebViewConfiguration,
              [instanceId, configurationInstanceId]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> removeDataOfTypes(
          int? instanceId,
          List<_i6.WKWebsiteDataTypesEnumData?>? dataTypes,
          double? secondsModifiedSinceEpoch) =>
      (super.noSuchMethod(
          Invocation.method(#removeDataOfTypes,
              [instanceId, dataTypes, secondsModifiedSinceEpoch]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
}
