// flag values from https://developer.android.com/reference/android/content/Intent.html
class Flag {
  static const int FLAG_ACTIVITY_BROUGHT_TO_FRONT = 4194304;
  static const int FLAG_ACTIVITY_CLEAR_TASK = 32768;
  static const int FLAG_ACTIVITY_CLEAR_TOP = 67108864;
  static const int FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET = 524288;
  static const int FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS = 8388608;
  static const int FLAG_ACTIVITY_FORWARD_RESULT = 33554432;
  static const int FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY = 1048576;
  static const int FLAG_ACTIVITY_LAUNCH_ADJACENT = 4096;
  static const int FLAG_ACTIVITY_MATCH_EXTERNAL = 2048;
  static const int FLAG_ACTIVITY_MULTIPLE_TASK = 134217728;
  static const int FLAG_ACTIVITY_NEW_DOCUMENT = 524288;
  static const int FLAG_ACTIVITY_NEW_TASK = 268435456;
  static const int FLAG_ACTIVITY_NO_ANIMATION = 65536;
  static const int FLAG_ACTIVITY_NO_HISTORY = 1073741824;
  static const int FLAG_ACTIVITY_NO_USER_ACTION = 262144;
  static const int FLAG_ACTIVITY_PREVIOUS_IS_TOP = 16777216;
  static const int FLAG_ACTIVITY_REORDER_TO_FRONT = 131072;
  static const int FLAG_ACTIVITY_RESET_TASK_IF_NEEDED = 2097152;
  static const int FLAG_ACTIVITY_RETAIN_IN_RECENTS = 8192;
  static const int FLAG_ACTIVITY_SINGLE_TOP = 536870912;
  static const int FLAG_ACTIVITY_TASK_ON_HOME = 16384;
  static const int FLAG_DEBUG_LOG_RESOLUTION = 8;
  static const int FLAG_EXCLUDE_STOPPED_PACKAGES = 16;
  static const int FLAG_FROM_BACKGROUND = 4;
  static const int FLAG_GRANT_PERSISTABLE_URI_PERMISSION = 64;
  static const int FLAG_GRANT_PREFIX_URI_PERMISSION = 128;
  static const int FLAG_GRANT_READ_URI_PERMISSION = 1;
  static const int FLAG_GRANT_WRITE_URI_PERMISSION = 2;
  static const int FLAG_INCLUDE_STOPPED_PACKAGES = 32;
  static const int FLAG_RECEIVER_FOREGROUND = 268435456;
  static const int FLAG_RECEIVER_NO_ABORT = 134217728;
  static const int FLAG_RECEIVER_REGISTERED_ONLY = 1073741824;
  static const int FLAG_RECEIVER_REPLACE_PENDING = 536870912;
  static const int FLAG_RECEIVER_VISIBLE_TO_INSTANT_APPS = 2097152;
}
