// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v1.0.16), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

/// The codec used by SharedPreferencesApi.
NSObject<FlutterMessageCodec> *SharedPreferencesApiGetCodec(void);

@protocol SharedPreferencesApi
- (nullable NSNumber *)removeKey:(NSString *)key error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)setBoolKey:(NSString *)key
                            value:(NSNumber *)value
                            error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)setDoubleKey:(NSString *)key
                              value:(NSNumber *)value
                              error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)setIntKey:(NSString *)key
                           value:(NSNumber *)value
                           error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)setStringKey:(NSString *)key
                              value:(NSString *)value
                              error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)setStringListKey:(NSString *)key
                                  value:(NSArray<NSString *> *)value
                                  error:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSNumber *)clearWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSDictionary<NSString *, id> *)getAllWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SharedPreferencesApiSetup(id<FlutterBinaryMessenger> binaryMessenger,
                                      NSObject<SharedPreferencesApi> *_Nullable api);

NS_ASSUME_NONNULL_END
